# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thrust.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ThrustStandMW(object):
    def setupUi(self, ThrustStandMW):
        ThrustStandMW.setObjectName(_fromUtf8("ThrustStandMW"))
        ThrustStandMW.resize(1022, 896)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ThrustStandMW.sizePolicy().hasHeightForWidth())
        ThrustStandMW.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(ThrustStandMW)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_main = QtGui.QWidget()
        self.tab_main.setObjectName(_fromUtf8("tab_main"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_main)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_main)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rb_manualControl = QtGui.QRadioButton(self.groupBox_2)
        self.rb_manualControl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rb_manualControl.setObjectName(_fromUtf8("rb_manualControl"))
        self.verticalLayout.addWidget(self.rb_manualControl)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.speedKnob = QtGui.QDial(self.groupBox_2)
        self.speedKnob.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedKnob.sizePolicy().hasHeightForWidth())
        self.speedKnob.setSizePolicy(sizePolicy)
        self.speedKnob.setMinimumSize(QtCore.QSize(150, 150))
        self.speedKnob.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.speedKnob.setMaximum(100)
        self.speedKnob.setObjectName(_fromUtf8("speedKnob"))
        self.horizontalLayout_5.addWidget(self.speedKnob)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lbl_currentSpeedValue = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_currentSpeedValue.sizePolicy().hasHeightForWidth())
        self.lbl_currentSpeedValue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_currentSpeedValue.setFont(font)
        self.lbl_currentSpeedValue.setObjectName(_fromUtf8("lbl_currentSpeedValue"))
        self.horizontalLayout_7.addWidget(self.lbl_currentSpeedValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.lbl_currentSpeedValueVar = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_currentSpeedValueVar.setFont(font)
        self.lbl_currentSpeedValueVar.setText(_fromUtf8(""))
        self.lbl_currentSpeedValueVar.setObjectName(_fromUtf8("lbl_currentSpeedValueVar"))
        self.horizontalLayout_10.addWidget(self.lbl_currentSpeedValueVar)
        self.lbl_percentManual = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_percentManual.setFont(font)
        self.lbl_percentManual.setObjectName(_fromUtf8("lbl_percentManual"))
        self.horizontalLayout_10.addWidget(self.lbl_percentManual)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.pb_lessSpeed = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_lessSpeed.sizePolicy().hasHeightForWidth())
        self.pb_lessSpeed.setSizePolicy(sizePolicy)
        self.pb_lessSpeed.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_lessSpeed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_lessSpeed.setText(_fromUtf8(""))
        self.pb_lessSpeed.setObjectName(_fromUtf8("pb_lessSpeed"))
        self.horizontalLayout_13.addWidget(self.pb_lessSpeed)
        self.txt_incrementSpeedValue = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_incrementSpeedValue.sizePolicy().hasHeightForWidth())
        self.txt_incrementSpeedValue.setSizePolicy(sizePolicy)
        self.txt_incrementSpeedValue.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_incrementSpeedValue.setFont(font)
        self.txt_incrementSpeedValue.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_incrementSpeedValue.setObjectName(_fromUtf8("txt_incrementSpeedValue"))
        self.horizontalLayout_13.addWidget(self.txt_incrementSpeedValue)
        self.pb_moreSpeed = QtGui.QPushButton(self.groupBox_2)
        self.pb_moreSpeed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_moreSpeed.setText(_fromUtf8(""))
        self.pb_moreSpeed.setObjectName(_fromUtf8("pb_moreSpeed"))
        self.horizontalLayout_13.addWidget(self.pb_moreSpeed)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lbl_InsertSpeedValue = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_InsertSpeedValue.setFont(font)
        self.lbl_InsertSpeedValue.setObjectName(_fromUtf8("lbl_InsertSpeedValue"))
        self.horizontalLayout_6.addWidget(self.lbl_InsertSpeedValue)
        self.txt_setSpeedValue = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_setSpeedValue.sizePolicy().hasHeightForWidth())
        self.txt_setSpeedValue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_setSpeedValue.setFont(font)
        self.txt_setSpeedValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_setSpeedValue.setObjectName(_fromUtf8("txt_setSpeedValue"))
        self.horizontalLayout_6.addWidget(self.txt_setSpeedValue)
        self.pb_setSpeedValue = QtGui.QPushButton(self.groupBox_2)
        self.pb_setSpeedValue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_setSpeedValue.setText(_fromUtf8(""))
        self.pb_setSpeedValue.setObjectName(_fromUtf8("pb_setSpeedValue"))
        self.horizontalLayout_6.addWidget(self.pb_setSpeedValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lbl_acceleration = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_acceleration.sizePolicy().hasHeightForWidth())
        self.lbl_acceleration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_acceleration.setFont(font)
        self.lbl_acceleration.setObjectName(_fromUtf8("lbl_acceleration"))
        self.horizontalLayout_11.addWidget(self.lbl_acceleration)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.rb_accEnabled = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_accEnabled.sizePolicy().hasHeightForWidth())
        self.rb_accEnabled.setSizePolicy(sizePolicy)
        self.rb_accEnabled.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rb_accEnabled.setText(_fromUtf8(""))
        self.rb_accEnabled.setObjectName(_fromUtf8("rb_accEnabled"))
        self.horizontalLayout_12.addWidget(self.rb_accEnabled)
        self.sb_acc = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_acc.sizePolicy().hasHeightForWidth())
        self.sb_acc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sb_acc.setFont(font)
        self.sb_acc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sb_acc.setProperty("value", 0.0)
        self.sb_acc.setObjectName(_fromUtf8("sb_acc"))
        self.horizontalLayout_12.addWidget(self.sb_acc)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.line_4 = QtGui.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_12.addWidget(self.line_4)
        self.rb_accDefault = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_accDefault.sizePolicy().hasHeightForWidth())
        self.rb_accDefault.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_accDefault.setFont(font)
        self.rb_accDefault.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rb_accDefault.setObjectName(_fromUtf8("rb_accDefault"))
        self.horizontalLayout_12.addWidget(self.rb_accDefault)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.pb_stopManualControl = QtGui.QPushButton(self.groupBox_2)
        self.pb_stopManualControl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_stopManualControl.setText(_fromUtf8(""))
        self.pb_stopManualControl.setObjectName(_fromUtf8("pb_stopManualControl"))
        self.horizontalLayout_8.addWidget(self.pb_stopManualControl)
        self.pb_startManualControl = QtGui.QPushButton(self.groupBox_2)
        self.pb_startManualControl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_startManualControl.setText(_fromUtf8(""))
        self.pb_startManualControl.setObjectName(_fromUtf8("pb_startManualControl"))
        self.horizontalLayout_8.addWidget(self.pb_startManualControl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.rb_autoControl = QtGui.QRadioButton(self.groupBox_2)
        self.rb_autoControl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rb_autoControl.setObjectName(_fromUtf8("rb_autoControl"))
        self.verticalLayout.addWidget(self.rb_autoControl)
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_linearAutoControl = QtGui.QWidget()
        self.tab_linearAutoControl.setObjectName(_fromUtf8("tab_linearAutoControl"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_linearAutoControl)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_finalSpeedValue = QtGui.QLabel(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_finalSpeedValue.sizePolicy().hasHeightForWidth())
        self.lbl_finalSpeedValue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_finalSpeedValue.setFont(font)
        self.lbl_finalSpeedValue.setObjectName(_fromUtf8("lbl_finalSpeedValue"))
        self.horizontalLayout_4.addWidget(self.lbl_finalSpeedValue)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.sldr_finalSpeedValue = QtGui.QSlider(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldr_finalSpeedValue.sizePolicy().hasHeightForWidth())
        self.sldr_finalSpeedValue.setSizePolicy(sizePolicy)
        self.sldr_finalSpeedValue.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sldr_finalSpeedValue.setMaximum(100)
        self.sldr_finalSpeedValue.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_finalSpeedValue.setObjectName(_fromUtf8("sldr_finalSpeedValue"))
        self.verticalLayout_8.addWidget(self.sldr_finalSpeedValue)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.lbl_finalSpeedValueVar = QtGui.QLabel(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_finalSpeedValueVar.sizePolicy().hasHeightForWidth())
        self.lbl_finalSpeedValueVar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_finalSpeedValueVar.setFont(font)
        self.lbl_finalSpeedValueVar.setText(_fromUtf8(""))
        self.lbl_finalSpeedValueVar.setObjectName(_fromUtf8("lbl_finalSpeedValueVar"))
        self.horizontalLayout_18.addWidget(self.lbl_finalSpeedValueVar)
        self.lbl_percentAuto = QtGui.QLabel(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_percentAuto.sizePolicy().hasHeightForWidth())
        self.lbl_percentAuto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_percentAuto.setFont(font)
        self.lbl_percentAuto.setObjectName(_fromUtf8("lbl_percentAuto"))
        self.horizontalLayout_18.addWidget(self.lbl_percentAuto)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.lbl_actualSpeed = QtGui.QLabel(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_actualSpeed.sizePolicy().hasHeightForWidth())
        self.lbl_actualSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_actualSpeed.setFont(font)
        self.lbl_actualSpeed.setText(_fromUtf8(""))
        self.lbl_actualSpeed.setObjectName(_fromUtf8("lbl_actualSpeed"))
        self.horizontalLayout_18.addWidget(self.lbl_actualSpeed)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.lbl_timeElapsed = QtGui.QLabel(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_timeElapsed.sizePolicy().hasHeightForWidth())
        self.lbl_timeElapsed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_timeElapsed.setFont(font)
        self.lbl_timeElapsed.setObjectName(_fromUtf8("lbl_timeElapsed"))
        self.horizontalLayout_16.addWidget(self.lbl_timeElapsed)
        self.sb_timeElapsed = QtGui.QDoubleSpinBox(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_timeElapsed.sizePolicy().hasHeightForWidth())
        self.sb_timeElapsed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sb_timeElapsed.setFont(font)
        self.sb_timeElapsed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sb_timeElapsed.setObjectName(_fromUtf8("sb_timeElapsed"))
        self.horizontalLayout_16.addWidget(self.sb_timeElapsed)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.prog_automaticControl = QtGui.QProgressBar(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prog_automaticControl.sizePolicy().hasHeightForWidth())
        self.prog_automaticControl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prog_automaticControl.setFont(font)
        self.prog_automaticControl.setProperty("value", 0)
        self.prog_automaticControl.setTextVisible(False)
        self.prog_automaticControl.setObjectName(_fromUtf8("prog_automaticControl"))
        self.verticalLayout_9.addWidget(self.prog_automaticControl)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.pb_stopAutoControl = QtGui.QPushButton(self.tab_linearAutoControl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_stopAutoControl.sizePolicy().hasHeightForWidth())
        self.pb_stopAutoControl.setSizePolicy(sizePolicy)
        self.pb_stopAutoControl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_stopAutoControl.setText(_fromUtf8(""))
        self.pb_stopAutoControl.setObjectName(_fromUtf8("pb_stopAutoControl"))
        self.horizontalLayout_17.addWidget(self.pb_stopAutoControl)
        self.pb_startAutoControl = QtGui.QPushButton(self.tab_linearAutoControl)
        self.pb_startAutoControl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_startAutoControl.setText(_fromUtf8(""))
        self.pb_startAutoControl.setObjectName(_fromUtf8("pb_startAutoControl"))
        self.horizontalLayout_17.addWidget(self.pb_startAutoControl)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.tabWidget_2.addTab(self.tab_linearAutoControl, _fromUtf8(""))
        self.tab_pidControl = QtGui.QWidget()
        self.tab_pidControl.setObjectName(_fromUtf8("tab_pidControl"))
        self.tabWidget_2.addTab(self.tab_pidControl, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.line_2 = QtGui.QFrame(self.tab_main)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox = QtGui.QGroupBox(self.tab_main)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.txt_log = QtGui.QTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_log.sizePolicy().hasHeightForWidth())
        self.txt_log.setSizePolicy(sizePolicy)
        self.txt_log.setMinimumSize(QtCore.QSize(0, 325))
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName(_fromUtf8("txt_log"))
        self.verticalLayout_7.addWidget(self.txt_log)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.cb_logEnable = QtGui.QCheckBox(self.groupBox)
        self.cb_logEnable.setObjectName(_fromUtf8("cb_logEnable"))
        self.horizontalLayout_14.addWidget(self.cb_logEnable)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.pb_restartBoard = QtGui.QPushButton(self.groupBox)
        self.pb_restartBoard.setText(_fromUtf8(""))
        self.pb_restartBoard.setObjectName(_fromUtf8("pb_restartBoard"))
        self.horizontalLayout_14.addWidget(self.pb_restartBoard)
        self.pb_clearLog = QtGui.QPushButton(self.groupBox)
        self.pb_clearLog.setText(_fromUtf8(""))
        self.pb_clearLog.setObjectName(_fromUtf8("pb_clearLog"))
        self.horizontalLayout_14.addWidget(self.pb_clearLog)
        self.pb_stopLog = QtGui.QPushButton(self.groupBox)
        self.pb_stopLog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_stopLog.setText(_fromUtf8(""))
        self.pb_stopLog.setObjectName(_fromUtf8("pb_stopLog"))
        self.horizontalLayout_14.addWidget(self.pb_stopLog)
        self.pb_startLog = QtGui.QPushButton(self.groupBox)
        self.pb_startLog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_startLog.setText(_fromUtf8(""))
        self.pb_startLog.setObjectName(_fromUtf8("pb_startLog"))
        self.horizontalLayout_14.addWidget(self.pb_startLog)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.list_availableCommands = QtGui.QListWidget(self.groupBox_3)
        self.list_availableCommands.setObjectName(_fromUtf8("list_availableCommands"))
        self.verticalLayout_5.addWidget(self.list_availableCommands)
        self.horizontalLayout_15.addWidget(self.groupBox_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.pb_addCommand = QtGui.QPushButton(self.groupBox)
        self.pb_addCommand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_addCommand.setText(_fromUtf8(""))
        self.pb_addCommand.setObjectName(_fromUtf8("pb_addCommand"))
        self.verticalLayout_4.addWidget(self.pb_addCommand)
        self.pb_eraseCommand = QtGui.QPushButton(self.groupBox)
        self.pb_eraseCommand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_eraseCommand.setText(_fromUtf8(""))
        self.pb_eraseCommand.setObjectName(_fromUtf8("pb_eraseCommand"))
        self.verticalLayout_4.addWidget(self.pb_eraseCommand)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.list_shownCommands = QtGui.QListWidget(self.groupBox_4)
        self.list_shownCommands.setObjectName(_fromUtf8("list_shownCommands"))
        self.verticalLayout_6.addWidget(self.list_shownCommands)
        self.horizontalLayout_15.addWidget(self.groupBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_19.addItem(spacerItem13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.lbl_portConnected = QtGui.QLabel(self.tab_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_portConnected.sizePolicy().hasHeightForWidth())
        self.lbl_portConnected.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_portConnected.setFont(font)
        self.lbl_portConnected.setText(_fromUtf8(""))
        self.lbl_portConnected.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_portConnected.setObjectName(_fromUtf8("lbl_portConnected"))
        self.verticalLayout_11.addWidget(self.lbl_portConnected)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab_main, _fromUtf8(""))
        self.tab_debugging = QtGui.QWidget()
        self.tab_debugging.setObjectName(_fromUtf8("tab_debugging"))
        self.tabWidget.addTab(self.tab_debugging, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        ThrustStandMW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ThrustStandMW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ThrustStandMW.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ThrustStandMW)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ThrustStandMW.setStatusBar(self.statusbar)

        self.retranslateUi(ThrustStandMW)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ThrustStandMW)

    def retranslateUi(self, ThrustStandMW):
        ThrustStandMW.setWindowTitle(_translate("ThrustStandMW", "ThrustStand", None))
        self.groupBox_2.setTitle(_translate("ThrustStandMW", "Speed Control", None))
        self.rb_manualControl.setText(_translate("ThrustStandMW", "Manual Control", None))
        self.lbl_currentSpeedValue.setText(_translate("ThrustStandMW", "Current Speed Value", None))
        self.lbl_percentManual.setText(_translate("ThrustStandMW", "%", None))
        self.lbl_InsertSpeedValue.setText(_translate("ThrustStandMW", "Insert Speed Value", None))
        self.lbl_acceleration.setText(_translate("ThrustStandMW", "Acceleration", None))
        self.rb_accDefault.setText(_translate("ThrustStandMW", "Default", None))
        self.rb_autoControl.setText(_translate("ThrustStandMW", "Automatic Control", None))
        self.lbl_finalSpeedValue.setText(_translate("ThrustStandMW", "Final speed Value", None))
        self.lbl_percentAuto.setText(_translate("ThrustStandMW", "%", None))
        self.lbl_timeElapsed.setText(_translate("ThrustStandMW", "Time elapsed", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_linearAutoControl), _translate("ThrustStandMW", "Linear Behaviour", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_pidControl), _translate("ThrustStandMW", "PID", None))
        self.groupBox.setTitle(_translate("ThrustStandMW", "Live Data", None))
        self.cb_logEnable.setText(_translate("ThrustStandMW", "Log data", None))
        self.groupBox_3.setTitle(_translate("ThrustStandMW", "Available Variables", None))
        self.groupBox_4.setTitle(_translate("ThrustStandMW", "Shown Variables", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("ThrustStandMW", "Thrust Analyser", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_debugging), _translate("ThrustStandMW", "Debug Mode", None))

